### ISSUE TITLE
How to get videos from a channel by it's ID?

### ISSUE THREAD

**Issue by milankragujevic** [simple-youtube/simple-youtube-api#21]

**Comment by milankragujevic** [comment]
Implemented with #22

**Comment by eorroe** [comment]
I was hoping to be able to do this today. Any updates on this?

**Comment by appellation** [comment]
This is already doable by using the [`search`](https://hypercoder2975.github.io/simple-youtube-api/master/YouTube.html#search) method.  Please see the relevant YouTube API [documentation](https://developers.google.com/youtube/v3/docs/search/list) for details.  Here's a code sample that might work.

```js
const videos = youtube.search(null, 10, { channelId: 'some channel id' });
```

**Comment by eorroe** [comment]
Nice! Thanks

Tip: Have you thought of making all methods accept an object so we can always pass named parameters instead.

I'm not a big fan of passing `fn(null, 10, {...})` I rather `fn({...})`.

No big deal, but just an idea for the next version 😉

Thanks again!

**Comment by appellation** [comment]
I'm looking at reworking the various method signatures for the next minor version to allow usage as you've described.  I'm also going to implement this method directly if #22 does not conform to my requests by then.
