### ISSUE TITLE
Custom request headers

### ISSUE THREAD

**Issue by nautonk** [simple-youtube/simple-youtube-api#28]
Hello @HyperCoder2975 ,

My youtube api used referer as a api filter, my question is how to make request using custom headers ?

I searching manual but no luck.

Sorry, my english is not good.

Thank you,

regards

**Comment by appellation** [comment]
It is currently not possible to use custom request headers with this module, as I am unaware of any API endpoints that use any headers other than authentication. What's your use case here?
