### ISSUE TITLE
[Request] Create TypeScript Declarations File

### ISSUE THREAD

**Issue by Favna** [simple-youtube/simple-youtube-api#33]
Currently when using this library in TypeScript it is... well.. let's just say, messy. This is because the library lacks an [Declarations file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) (`index.d.ts`). 

Recommended:

1. Create a folder `typings` and in it a file `index.d.ts`
2. To `package.json` add `"typings": "./typings/index.d.ts"`
3. Populate `index.d.ts` with all the required data

I've given it a shot myself but not knowing the inner workings of the library makes this really hard so I just got stumped.

**Comment by OscarXcore** [comment]
Oh jeez. I just realised you made this issue 5 hours ago. I had it finished around the time you made this. I had to delay the pull request because work calls.

**Comment by Favna** [comment]
Seeing as the PR for this exists I'm just going to close the issue. Would be nice if the PR gets revived so to say but at least for now I just dug into the Youtube Data API docs and wrote my own `fetch`-es

**Comment by appellation** [comment]
Leave this open until the PR is merged.
