### ISSUE TITLE
I cant get the sub count of a channel in a setInterval loop

### ISSUE THREAD

**Issue by Brent-Trenholme** [simple-youtube/simple-youtube-api#47]
Idk if it's that the module isn't working properly or I don't know what I'm doing but when I use this code
setInterval(()=>{
    let subUpdate
    youtube.getChannelByID(channelId,{part:"statistics"})
    .then(channel=>{
        subUpdate=channel.subscriberCount
    })
    if(subs<subUpdate)tts.speak("a mistake has been made");
    subs=subUpdate
    console.log(subs)
},9000);
it says the subcount is undefined, am I missing something?

**Comment by appellation** [comment]
This is an issue with your asynchronous code, not the library. I recommend [reading up a bit](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises) on it. Essentially the result of the query is not immediately available in the outer scope of the `then` callback.
