### ISSUE TITLE
if (typeof key !== 'string') throw new Error('The YouTube API key you provided was not a string.');

### ISSUE THREAD

**Issue by FEH-SAMA** [simple-youtube/simple-youtube-api#48]
Hello hello I have an error on line 26, and I can't solve it already I tried to install past versions but it gives error too!

if (typeof key !== 'string') throw new Error('The YouTube API key you provided was not a string.');
                                     ^

Error: The YouTube API key you provided was not a string.

**Comment by appellation** [comment]
Ensure that the YouTube API key you are providing is a string.

**Comment by FEH-SAMA** [comment]
Okay, thanks I had forgotten to pass the key!
